-- BiteJoy schema, migration 0012: make `saved_restaurants.restaurant_id`
-- an opaque identifier instead of a hard foreign key to `restaurants`.
--
-- Why: `restaurants.id` is a uuid generated by Postgres for rows actually
-- seeded into this table (see packages/db/seed). But Stage 2's MCP server
-- defaults to `BITEJOY_PROVIDER=fictional`, which serves restaurants from
-- an in-memory dataset with its own string ids ("r_flame_fork", ...) and
-- never touches this table at all; the Google Places provider (when
-- enabled) uses ids like "gp_<place id>". A hard `uuid references
-- restaurants(id)` FK rejects every one of those - saving a restaurant a
-- user actually found via search would always fail. `restaurant_id` is
-- therefore an opaque, provider-defined string: still unique per
-- (user_id, restaurant_id), still indexed, just not FK-enforced against a
-- table that isn't the source of truth for restaurant identity in this
-- architecture. Enriching a saved id back into a display-ready card is the
-- calling provider's job (see apps/mcp-server's savedRestaurantView.ts /
-- apps/web's restaurants/lookup.ts), not the database's.

-- Dropped by definition-content lookup, not the assumed default-naming
-- convention - 0008's near-identical assumption for a check constraint
-- turned out wrong on a live run, so this one isn't trusted either.
do $$
declare
  c record;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'saved_restaurants'::regclass
      and contype = 'f'
      and pg_get_constraintdef(oid) ilike '%restaurant_id%'
  loop
    execute format('alter table saved_restaurants drop constraint %I', c.conname);
  end loop;
end $$;

alter table saved_restaurants alter column restaurant_id type text;
