import type { RestaurantCard } from "../../types.js";

export function makeCard(overrides: Partial<RestaurantCard> = {}): RestaurantCard {
  return {
    id: "r_flame_fork",
    slug: "flame-and-fork",
    name: "Flame & Fork",
    image: undefined,
    cuisines: ["burgers", "american"],
    area: "East Croydon",
    city: "Croydon",
    address: "12 Dingwall Road, Croydon",
    location: { lat: 51.3757, lng: -0.0921 },
    distanceKm: 0.4,
    travelTimeMinutes: 5,
    travelMode: "walking",
    priceLevel: "moderate",
    pricePerPersonGbp: 28,
    popularFoodPrices: [{ name: "Double Smash Burger", priceGbp: 13.5 }],
    popularDrinkPrices: [{ name: "Smoked Old Fashioned", priceGbp: 9.5 }],
    offers: [{ title: "Free starter for groups of 4+", type: "group_offer", validUntil: "2026-12-01T00:00:00.000Z", isVerified: true }],
    openingStatus: "open_now",
    rating: 4.6,
    reviewCount: 812,
    popularDishes: ["Double Smash Burger", "Fire-Roasted Cauliflower Burger"],
    dietaryOptions: ["vegetarian", "gluten_free"],
    atmosphere: ["lively", "casual"],
    facilities: ["parking", "large_groups"],
    isIndependent: true,
    isNewOpening: false,
    matchScorePercent: 87,
    reasons: ["Serves burgers", "About £28 per person, within your £30 budget", "Has parking"],
    dataFreshness: { label: "Checked 4h ago", source: "fictional_demo", isVerified: true, lastCheckedAt: "2026-08-02T18:00:00.000Z" },
    bookingUrl: "https://booking.bitejoy.app/demo/flame-and-fork",
    orderingUrl: "https://order.bitejoy.app/demo/flame-and-fork",
    website: "https://flameandfork.example.com",
    ...overrides,
  };
}
